version: '3'
services:
  react-app:
    build: .
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - REACT_APP_CRUD_API_URL=http://194.87.190.42:8080
    restart: always
